name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Base metrics
        uses: lowlighter/metrics@latest
        with:
          filename: images/metrics/base-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_twemoji: yes
          plugin_lines: yes
          plugin_isocalendar: yes
#           plugin_isocalendar_duration: full-year
          plugin_gists: yes
          repositories_forks: yes
          config_timezone: Asia/Taipei
          config_order: base.header, isocalendar, base.repositories, base.activity, base.community, gist, base.metadata
          config_padding: 6%
      - name: Activity metrics
        uses: lowlighter/metrics@latest
        with:
          filename: images/metrics/activity-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_twemoji: yes
          plugin_languages: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_skipped: jim60105/Playlists, jim60105/jim60105
          plugin_activity_load: 300
          plugin_activity_visibility: all
          base: ""
          repositories_forks: yes
          config_timezone: Asia/Taipei
          config_order: activity, language
          config_padding: 6%
      - name: Habits metrics
        uses: lowlighter/metrics@latest
        with:
          filename: images/metrics/habits-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_twemoji: yes
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          base: ""
          repositories_forks: yes
          config_timezone: Asia/Taipei
          config_padding: 6%
      - name: Blog metrics
        uses: lowlighter/metrics@latest
        with:
          filename: images/metrics/blog.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_twemoji: yes
          plugin_rss: yes
          plugin_rss_limit: 5
          plugin_rss_source: https://blog.maki0419.com/feeds/posts/default
          base: ""
          repositories_forks: yes
          config_timezone: Asia/Taipei
          config_padding: 6%
      - name: wakatime metrics
        uses: lowlighter/metrics@latest
        with:
          filename: images/metrics/wakatime.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_twemoji: yes
          plugin_wakatime: yes
          plugin_wakatime_days: 7
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_sections: time, editors, os
          plugin_wakatime_url: https://wakatime.com
          plugin_wakatime_user: jim60105
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          base: ""
          repositories_forks: yes
          config_timezone: Asia/Taipei
          config_padding: 6%
      - name: Achievements metrics
        uses: lowlighter/metrics@latest
        with:
          filename: images/metrics/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_twemoji: yes
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: B
          base: ""
          repositories_forks: yes
          config_timezone: Asia/Taipei
          config_padding: 6%