name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: 
      - master
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Base metrics
        uses: lowlighter/metrics@latest
        with:
          filename: base-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: "header, repositories"
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_gists: yes
          repositories_forks: yes
          config_timezone: Asia/Taipei
          config_order: base.header, isocalendar, base.repositories, gist
          config_padding: 6%
      - name: Activity metrics
        uses: lowlighter/metrics@latest
        with:
          filename: activity-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_languages: yes
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          repositories_forks: yes
          config_timezone: Asia/Taipei
          config_order: activity, language
          config_padding: 6%
      - name: Habits metrics
        uses: lowlighter/metrics@latest
        with:
          filename: habits-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          repositories_forks: yes
          config_timezone: Asia/Taipei
          config_padding: 6%
